# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= dsi_hello_world_blockds
GAME_TITLE	:= Hello World DSi - Working!
GAME_SUBTITLE	:= Gurt

# Source code paths

# GFXDIRS		= graphics

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
