# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS    ?= /opt/blocksds/core

# User config

NAME        := qr_test_parse
GAME_TITLE  := QR Parse Test
GAME_SUBTITLE   := Gurt

# Source code paths
# GFXDIRS       = graphics

# Libraries to link (Order matters: -lfat must come before -lnds9)
# LIBS        := -lnds9

# Include the BlocksDS compilation rules
include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile